name: Build Docker Image

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Extract version from tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t dockerreg.gruppe.ai/stemgraph-online-api:${{ env.VERSION }} -f ./Dockerfile .
          docker push dockerreg.gruppe.ai/stemgraph-online-api:${{ env.VERSION }}

      - name: Update docker-compose.yml with new image tag
        run: |
          sed -i "s|image: dockerreg.gruppe.ai/stemgraph-online-api:.*|image: dockerreg.gruppe.ai/stemgraph-online-api:${{ env.VERSION }}|" docker-compose.yml
